# TODO: 1. UPDATE PATH TO THE TRAIN/VAL/TEST METADATA FILES
# TODO: 2. REMEMBER TO UPDATE BEST MODEL GOT FROM STAGE-2 PRE-TRAINING

# CLORE
python train_owl_vit.py --model owlvit-base-patch32 --dataset bird_soup --sub_datasets all --descriptors chatgpt --prompt_type 0 --batch_size 32 --save_freq 1 --num_workers 8 --devices 0 --epochs 5 --lr 0.00002 --weight_decay 0.001 --project_name finetuning --loss_weights 0,1,1,1,1 --network_type classification --classification_loss ce_loss --early_stopping 5 --train_file "../data/bird_11K/metadata/level_3_exclude_cub/clore_split/train_reindexed.h5" --val_file "../data/bird_11K/metadata/level_3_exclude_cub/clore_split/val_reindexed.h5" --test_file "../data/bird_11K/metadata/level_3_exclude_cub/clore_split/test_unseen_reindexed.h5" --best_model "" --birdsoup_level 3 --finetuning "vision_encoder_mlp" --note "all_components_cub_clore"

# SCS/SCE - CUB EASY
python train_owl_vit.py --model owlvit-base-patch32 --dataset bird_soup --sub_datasets all --descriptors chatgpt --prompt_type 0 --batch_size 32 --save_freq 1 --num_workers 8 --devices 1 --epochs 5 --lr 0.00002 --weight_decay 0.001 --project_name finetuning --loss_weights 0,1,1,1,1 --network_type classification --classification_loss ce_loss --early_stopping 5 --train_file "../data/bird_11K/metadata/level_3_exclude_cub/super_category_split/easy_train_reindexed.h5" --val_file "../data/bird_11K/metadata/level_3_exclude_cub/super_category_split/easy_val_reindexed.h5" --test_file "../data/bird_11K/metadata/level_3_exclude_cub/super_category_split/easy_test_reindexed.h5" --best_model "" --birdsoup_level 3 --finetuning "vision_encoder_mlp" --note "all_components_cub_easy"

# SCS/SCE - CUB HARD
python train_owl_vit.py --model owlvit-base-patch32 --dataset bird_soup --sub_datasets all --descriptors chatgpt --prompt_type 0 --batch_size 32 --save_freq 1 --num_workers 8 --devices 2 --epochs 5 --lr 0.00002 --weight_decay 0.001 --project_name finetuning --loss_weights 0,1,1,1,1 --network_type classification --classification_loss ce_loss --early_stopping 5 --train_file "../data/bird_11K/metadata/level_3_exclude_cub/super_category_split/hard_train_reindexed.h5" --val_file "../data/bird_11K/metadata/level_3_exclude_cub/super_category_split/hard_val_reindexed.h5" --test_file "../data/bird_11K/metadata/level_3_exclude_cub/super_category_split/hard_test_reindexed.h5" --best_model "" --birdsoup_level 3 --finetuning "vision_encoder_mlp" --note "all_components_cub_hard"

# SCS/SCE - NABirds EASY
python train_owl_vit.py --model owlvit-base-patch32 --dataset bird_soup --sub_datasets all --descriptors chatgpt --prompt_type 0 --batch_size 32 --save_freq 1 --num_workers 8 --devices 3 --epochs 5 --lr 0.00002 --weight_decay 0.001 --project_name finetuning --loss_weights 0,1,1,1,1 --network_type classification --classification_loss ce_loss --early_stopping 5 --train_file "../data/bird_11K/metadata/level_3_exclude_nabirds/super_category_split/easy_train_reindexed.h5" --val_file "../data/bird_11K/metadata/level_3_exclude_nabirds/super_category_split/easy_val_reindexed.h5" --test_file "../data/bird_11K/metadata/level_3_exclude_nabirds/super_category_split/easy_test_reindexed.h5" --best_model "" --birdsoup_level 3 --finetuning "vision_encoder_mlp" --note "all_components_nabirds_easy"

# SCS/SCE - NABirds HARD
python train_owl_vit.py --model owlvit-base-patch32 --dataset bird_soup --sub_datasets all --descriptors chatgpt --prompt_type 0 --batch_size 32 --save_freq 1 --num_workers 8 --devices 4 --epochs 5 --lr 0.00002 --weight_decay 0.001 --project_name finetuning --loss_weights 0,1,1,1,1 --network_type classification --classification_loss ce_loss --early_stopping 5 --train_file "../data/bird_11K/metadata/level_3_exclude_nabirds/super_category_split/hard_train_reindexed.h5" --val_file "../data/bird_11K/metadata/level_3_exclude_nabirds/super_category_split/hard_val_reindexed.h5" --test_file "../data/bird_11K/metadata/level_3_exclude_nabirds/super_category_split/hard_test_reindexed.h5" --best_model "" --birdsoup_level 3 --finetuning "vision_encoder_mlp" --note "all_component_nabirds_hard"
